### ISSUE TITLE
Save state slot changes every time I save - How to select the save state slot? 

### ISSUE THREAD

**Issue by sirguigui** [retrogamecorps/s30-add-on-pack#10]
I have installed the latest version of the add-on-pack and I am not sure how to use the expanded save state capacity of it. Every time I save on the snes emulator, it changes to the next save state slot and I am not able to load the save state from the slot I had just saved.

Is there a way of choosing what slot I want to save/load in?

Thank you very much for the excellent work!

**Comment by retrogamecorps** [comment]
I had it switched to auto index based on advice from another user, but you're right that it just keeps going to the next save state, which makes it hard to load.  I've reverted it back, if you grab this new one here (right-click on the "Raw" button and select Save As...) you can overwrite the existing retroarch-nes.cfg file and it'll fix the SNES saves.

https://github.com/retrogamecorps/s30-add-on-pack/blob/main/retro/retroarch-nes.cfg

Or just open the existing retroarch-nes.cfg file on your card and replace this line:

savestate_auto_index = "false"

**Comment by sirguigui** [comment]
Thank you very much retrogamecorps.
