### ISSUE TITLE
SNES core creates .srm file in the roms folder as soon as I open a game and when a save state is saved the .state file is placed inside the roms folder

### ISSUE THREAD

**Issue by sirguigui** [retrogamecorps/s30-add-on-pack#11]
This behavior is filling the roms folder with extra files. I think this behavior was not in the earlier versions. Is this change made so that the save files will not corrupt anymore? Is there a way to change it so these files would be in a different folder?

Thank you very much for the great work!

**Comment by retrogamecorps** [comment]
I just looked and the file is set up correctly.  Make sure you have created a folder in the root directory called "saves" (this is a new step from v1.5 of the add-on pack and beyond) and that you're using the most recent version of the retroarch-nes.cfg file and the sections/emulators/06 snes9x2010 (SNES) file.  Once properly set up, all of your save files will go into that "saves" folder.

https://github.com/retrogamecorps/s30-add-on-pack/blob/main/retro/retroarch-nes.cfg
https://github.com/retrogamecorps/s30-add-on-pack/blob/main/emulators/06%20snes9x2010%20(SNES)

Let me know if the issue keeps happening, I'll leave this open for now.

**Comment by sirguigui** [comment]
Creating the saves file fixed it. I had updated it from the 1.4 just by looking at the instructions in the Changelog and had not seen that step in the README. Thanks.
