### ISSUE TITLE
Input button codes

### ISSUE THREAD

**Issue by Dantasstic** [retrogamecorps/s30-add-on-pack#13]
Do you know the input button codes for each button on the device? 

I like mapping the X button as a secondary B button in Nintendo emulators that don't have actually use X or Y; Game Boy, Game Boy Color, NES, GBA

**Comment by retrogamecorps** [comment]
Hi, you can go in to the retroarch.cfg file for any individual system and enable turbo or secondary buttons in the input code.  Here are the keymap codes for each button.  Note that many systems use the same config file (like the retroarch-nes.cfg file is used for almost all console systems, so messing with that config will also affect SNES, etc).  So your best bet would be to make a retroarch-nes1.cfg duplicate file and point the sections/emulators/04 fceumm (NES) code to that cfg file instead specifically for NES.

A=x
B=z
X=s
Y=a
R1=w
L1=q
SELECT = rshift
START= Enter

**Comment by Dantasstic** [comment]
What is the line to search for for secondary input for each button? I can't seem to find that...

**Comment by retrogamecorps** [comment]
Ah, good point.  Try using a comma, so like "z,s" or "z, s" and seeing if one of those works.

**Comment by Dantasstic** [comment]
> 
> 
> Ah, good point. Try using a comma, so like "z,s" or "z, s" and seeing if one of those works.

No go with either, unfortunately.... damn shame
