### ISSUE TITLE
Game Boy Aspect Ratio

### ISSUE THREAD

**Issue by Dantasstic** [retrogamecorps/s30-add-on-pack#14]
I believe that setting GB and GBC to 

aspect_ratio_index = "20"

is much closer to the original systems ratio than to have it set to "6" as it currently is in the pack. 

6 is too narrow and you can see this by how the tertiminos in Tetris look squished, whereas they look much better at 20.

**Comment by retrogamecorps** [comment]
I agree, it looks better.  Thanks for the find, I've implemented the changes and they'll be in the next update.
