### ISSUE TITLE
ZX Spectrum

### ISSUE THREAD

**Issue by impydave** [retrogamecorps/s30-add-on-pack#15]
Hi all, 

Can anyone help with the ZX Spectrum emu? For the life of me I can't start any game, even Manic Miner, says press enter, but nothing works, other games ask for keyboard presses, is there a virtual keyboard I'm missing?

Thanks

Dave

**Comment by retrogamecorps** [comment]
Unfortunately we cannot set or modify a remap file for our cores at this time, which means we cannot map a button to the ENTER key on ZX Spectrum.  So the number of playable games on this system will be limited until we can get a full RetroArch running on the device.
