### ISSUE TITLE
Bios rom problems

### ISSUE THREAD

**Issue by supertombrother** [retrogamecorps/s30-add-on-pack#16]
I put famicom disk system bios roms into the bios folder, but the famicom disk system emulator won't work. I then went and unzipped all the bios files and now the fds emulator just shows a gray screen when I load a rom. Any help with bios would be appreciated.

**Comment by retrogamecorps** [comment]
I would wager that you need to try a different disksys.rom file, maybe the one you are using it's compatible with this RetroArch core.  Definitely keep your FDS roms zipped!  Once you get them working, you will need to tap (or maybe double-tap) the L1 button to swap disks.
