### ISSUE TITLE
Settings menu broken

### ISSUE THREAD

**Issue by bkacjios** [retrogamecorps/s30-add-on-pack#17]
I just got my system today, and it apparently came preinstalled with this addon pack with on the SD card, but only 1.2. I figured I'd update it to the latest and followed the instructions, but now the systems settings menu (where you change the brightness) is just a black screen.

Any idea on how to fix this?

**Comment by retrogamecorps** [comment]
I'm not sure what's going on.  I would try this:

Unzip and add these two files to the 'bin' folder on your SD card:
[bin.zip](https://github.com/retrogamecorps/s30-add-on-pack/files/5899330/bin.zip)

Unzip and add this file to the skins/Default/wallpapers folder on your SD card:
[joycalib.zip](https://github.com/retrogamecorps/s30-add-on-pack/files/5899332/joycalib.zip)

Overwrite any files when prompted.  Hopefully that will help.

**Comment by bkacjios** [comment]
I already had those files, but I overwrote them anyway, but was still getting a black screen. I found it's settings_bg.png causing it to break, maybe because it's a smaller resolution? I just copied and replaced it with game_bg.png and now it works.

**Comment by retrogamecorps** [comment]
That is odd, the settings_bg.png in my repo is the same 480x320 as my other files, maybe they are shipping with a different file.  Either way, I'm glad to hear that you got it sorted!
