### ISSUE TITLE
Second player problem

### ISSUE THREAD

**Issue by supertombrother** [retrogamecorps/s30-add-on-pack#19]
I tried to play super mario all-stars on the SNES emulator, but when I chose two players, it didn't let me control the second player. Is there a hotkey combination to switch controllers? Playing as luigi would be nice.

**Comment by retrogamecorps** [comment]
If you'd like, you could go into the emus/retro/retroarch-nes.cfg file and match all of the input_player2 values to those found in input_player1 lines.  This will mean that every time you press a button, it will trigger it for both Player 1 and Player 2.  That should make it work for Super Mario All-Stars, but I cannot be held responsible for how it will mess up other games :). For example, any game where the second player can join by pressing START, a second player will join when you press START when playing as Player 1.  Unfortunately there is no ability to create per-game settings at this time.
