### ISSUE TITLE
More setting options in Retroarch Cores?

### ISSUE THREAD

**Issue by Donobi** [retrogamecorps/s30-add-on-pack#2]
When I press power button in SNES or other emulators I only have resume, restart, save, load and close option. Is there any way to have more than that? Any combination of buttons to show me more settings? Like turn on rewind in NES or SNES games, change save slots, enable cheats or change button mapping? Sorry for bothering you I'm new to this kind of devices. With your guide you make this pocket go great retro handheld and thank you very much for that:)

**Comment by retrogamecorps** [comment]
Unfortunately the RetroArch interface is controlled by the firmware, which is flashed onto the device itself and not the card.  So manipulating the card contents (which is what I did to upgrade the emulators and wallpapers) won't work.  I'd love to be able to set those features, or allow for scaling options in the menu, but it's not possible through this add-on pack (and my skill level!).

**Comment by Donobi** [comment]
Oh ok thx for reply:) I was trying to change some options in retroarch CFG file but it didnt work of course ( like quick_menu_show_options change from "false" to "true" xD ). Thanks again for your guide!:)

**Comment by retrogamecorps** [comment]
We have a full RetroArch working now and will be in my next release.  Closing!
