### ISSUE TITLE
More Than One Save State Per Core

### ISSUE THREAD

**Issue by deusxmach1na** [retrogamecorps/s30-add-on-pack#4]
I'm not sure if the issue overwriting saves is the emu state or the game save.  I did get more than one save state per core working by changing this setting from false to true:
```
savestate_auto_index = "true"
```

**Comment by retrogamecorps** [comment]
Thanks for this, I'll add it to the code!

**Comment by deusxmach1na** [comment]
Thanks for doing all the hard work and documenting it. I’ll keep fiddling with configs trying to get L2 and R2 going.
