### ISSUE TITLE
DMG Game Boy "Green color"

### ISSUE THREAD

**Issue by Dantasstic** [retrogamecorps/s30-add-on-pack#6]
If the issue of retaining a permanent core-options config file is ever figured out, the correct green color of the DMG Game Boy should be set to:  

gambatte_gb_internal_palette = "GB - DMG" 

in the config, and not to "Special 1"

**Comment by retrogamecorps** [comment]
Hi, this is deliberate and something I mention in my add-on pack video.  The DMG palette is too intense on this screen for my tastes.  If you like the DMG one then feel free to adjust to your liking (which it sounds like you figured out!).
