### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by TetrisSQC** [retrogamecorps/s30-add-on-pack#9]
Hi, 

I tried to get retroarch xmb running, but unluckily failed to do so. Anyway I decided to port the epic noir theme to the machine. In order not to paint every image by myself I wrote a theme renderer which does the thing automated. 

I will probably change the text size a bit since it seem too small, but there is plenty of space left so it can be easily achieved.
![snes](https://user-images.githubusercontent.com/11291557/105986002-92dc2e00-609c-11eb-8942-896a3addefc2.png)
[epicnoir.zip](https://github.com/retrogamecorps/s30-add-on-pack/files/5886607/epicnoir.zip)

If you have suggestions, feel free to tell them.

**Comment by retrogamecorps** [comment]
Hi, this is pretty great!  The only issue I see is that some of the titles get cut off (if they are more than one word.  So SNES just says Nintendo, and NES just says System.  I think a bit bigger text in the description would be awesome, too!

**Comment by TetrisSQC** [comment]
Oh thanks for the response. Yes I will check them and reupload it again. I forgot the first system line in the theme.xml. It should fit now. I did not tested them at the moment on my device, since I had some dust grains on the display which I want to remove first :) Not sure if the explanation text is too small.

![nes](https://user-images.githubusercontent.com/11291557/105986103-b8693780-609c-11eb-9968-85e4e75f4ce1.png)

**Comment by TetrisSQC** [comment]
I created a final version with a thicker font and it looks quite epic. I also added a settings image and one for tic80. 
[epicnoir.zip](https://github.com/retrogamecorps/s30-add-on-pack/files/5882676/epicnoir.zip)
![processed](https://user-images.githubusercontent.com/11291557/106045865-d1480c00-60e1-11eb-824a-9f397c177ab2.jpeg)

The next step will be to change the font and the content background image. I post the result in here after all.

**Comment by retrogamecorps** [comment]
Hi I just looked through them, they look great!  The only suggestions I would have as you go through (and are by no means necessary):

- There is an FBA wallpaper but the emulator on this device is FBN, if you're able to change the text in the xml to FinalBurn Neo that would be awesome.  Also, the SFII image from the PCE wallpaper might be more appropriate (and easier on the eyes) than the default bloody Haggar image.
- Neo Geo and NGPC have the same (Metal Slug) image, but you could swap out one of them with the Fatal Fury image from Neo Geo CD to differentiate them.
- Sega CD/32X have the same (DOOM) image, but to differentiate, you could change the Sega CD image (which didn't even have DOOM as a release!) to the Daphne (Dragon's Lair) image instead, or maybe the Monkey Island image from ScummVM.
- Same with TG16/TGCD/ZXSpectrum, they have the same Castlevania image.  Only the TGCD makes sense with that image.  The ZXSpectrum could use the Apple II image of Prince of Persia instead.  Not sure about what to put on the TG16, although the PC98 image of Dragon Slayer or the Master System image of Space Harrier could work.

Thanks for all your work on this!

**Comment by Dantasstic** [comment]
This is sweet! File names need to be adjusted to work with the pack though. Should be gg.png for Game Gear and sms.png for Sega Master System. 

The text for the game names in the upper right corner is basically too small to read on the S30 screen

**Comment by TetrisSQC** [comment]
Thanks for the positive feedback. I partially updated your suggestions. I honestly did not saw this before you mentioned it, since I just wrote a renderer for these kind of themes. I will reupload the zip later today with all the patches. 

Cheers

**Comment by TetrisSQC** [comment]
I've updated the zip file in the first post. It contains a sub directory with the wallpapers. I also tried to create a customized settings background and for the game window. I have no idea why it turns the view into black, so I kept it untouched at the moment. 
The images for Final Burn Neo, ZX Spectrum, TG16, TGCD and Sega32 are also replaced.

**Comment by retrogamecorps** [comment]
Thanks so much, I've added it to the code!
